salesforce.settings:
  type: config_object
  label: 'Salesforce Settings'
  mapping:
    use_latest:
      type: boolean
      label: 'Use latest REST API Version by default'
    rest_api_version:
      type: mapping
      label: 'REST API Version'
      mapping:
        label:
          type: string
          label: 'Label'
        url:
          type: string
          label: 'URL'
        version:
          type: string
          label: 'Version'
